version:  '3.7'

networks:
  backend:

volumes:
  db_data:

services:

  db:
    image: mariadb:10.4.12
    restart: on-failure
    networks:
      - backend
    volumes:
      - type: bind
        source: ./docker/mysql/data
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    ports:
      - "3306:3306"

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    networks:
      - backend
    volumes:
      - type: bind
        source: ./apps/${APP_NAME}/public/
        target: /usr/src/app
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php
      - db

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        DEVELOPER_NAME: ${DEVELOPER_NAME}
    restart: on-failure
    networks:
      - backend
    volumes:
      - type: bind
        source: ./apps/${APP_NAME}
        target: /app
#    user: 1000:1000