version:  '3.7'

networks:
  backend:

services:

  db:
    image: mariadb:10.4.12
    restart: on-failure
    networks:
      - backend
    volumes:
      - type: bind
        source: ./docker/db/mysql
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    ports:
      - "3306:3306"

  redis:
    image: bitnami/redis:5.0
    environment:
      REDIS_PASSWORD: redis123
    networks:
      - backend
    ports:
      - 6379:6379

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    networks:
      - backend
    volumes:
      - type: bind
        source: ./apps/${APP_NAME}/public/
        target: /usr/src/app
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USERNAME: ${USERNAME}
    environment:
      JWT_SECRET_KEY: /app/config/jwt/private.pem
      JWT_PUBLIC_KEY: /app/config/jwt/public.pem
      JWT_PASSPHRASE: passphrase
    restart: on-failure
    networks:
      - backend
    volumes:
      - type: bind
        source: ./apps/${APP_NAME}
        target: /app
    depends_on:
      - db
      - redis