version:  '3.7'

networks:
  backend:

services:

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev123
      - PGDATA=/var/lib/postgresql/data/my_data
    restart: on-failure
    networks:
      - backend
    volumes:
      - ./docker/db/postgresql:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
#    image: mariadb:10.4.12
#    restart: on-failure
#    networks:
#      - backend
#    volumes:
#      - type: bind
#        source: ./docker/db/mysql
#        target: /var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: main_db
#      MYSQL_USER: dev
#      MYSQL_PASSWORD: dev123
#    ports:
#      - "3306:3306"

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    networks:
      - backend
    volumes:
      - type: bind
        source: ./apps/${APP_NAME}/public/
        target: /usr/src/app
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php
      - db

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USERNAME: ${USERNAME}
    restart: on-failure
    networks:
      - backend
    volumes:
      - type: bind
        source: ./apps/${APP_NAME}
        target: /app